# Generated by Django 5.1.4 on 2025-02-01 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalpost',
            options={'ordering': ['-is_pinned', '-created_at'], 'verbose_name': '일반 게시글', 'verbose_name_plural': '일반 게시글 목록'},
        ),
        migrations.AlterModelOptions(
            name='readingtippost',
            options={'ordering': ['-is_pinned', '-created_at'], 'verbose_name': '독서 팁 게시글', 'verbose_name_plural': '독서 팁 게시글 목록'},
        ),
        migrations.AddField(
            model_name='book',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='조회수'),
        ),
        migrations.AlterField(
            model_name='bookeventpost',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community.book', verbose_name='책'),
        ),
        migrations.AlterField(
            model_name='bookeventpost',
            name='category',
            field=models.CharField(choices=[('book_post', '책 게시글'), ('reading_group_post', '독서 모임'), ('book_review_event', '서평 이벤트'), ('book_talk_post', '북토크'), ('personal_event_post', '개인 이벤트')], default='book_post', help_text='게시글 유형 선택', max_length=50, verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='bookeventpost',
            name='content',
            field=models.TextField(verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='bookeventpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='등록일'),
        ),
        migrations.AlterField(
            model_name='bookeventpost',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='활성화 여부'),
        ),
        migrations.AlterField(
            model_name='bookeventpost',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='삭제 여부'),
        ),
        migrations.AlterField(
            model_name='bookeventpost',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='고정 여부'),
        ),
        migrations.AlterField(
            model_name='bookeventpost',
            name='tags',
            field=models.ManyToManyField(blank=True, to='community.posttag', verbose_name='태그'),
        ),
        migrations.AlterField(
            model_name='bookeventpost',
            name='title',
            field=models.CharField(max_length=200, verbose_name='제목'),
        ),
        migrations.AlterField(
            model_name='bookeventpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
        migrations.AlterField(
            model_name='bookeventpost',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='조회수'),
        ),
        migrations.AlterField(
            model_name='generalpost',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community.book', verbose_name='책'),
        ),
        migrations.AlterField(
            model_name='generalpost',
            name='category',
            field=models.CharField(choices=[('book_post', '책 게시글'), ('reading_group_post', '독서 모임'), ('book_review_event', '서평 이벤트'), ('book_talk_post', '북토크'), ('personal_event_post', '개인 이벤트')], default='book_post', help_text='게시글 유형 선택', max_length=50, verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='generalpost',
            name='content',
            field=models.TextField(verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='generalpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='등록일'),
        ),
        migrations.AlterField(
            model_name='generalpost',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='활성화 여부'),
        ),
        migrations.AlterField(
            model_name='generalpost',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='삭제 여부'),
        ),
        migrations.AlterField(
            model_name='generalpost',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='고정 여부'),
        ),
        migrations.AlterField(
            model_name='generalpost',
            name='tags',
            field=models.ManyToManyField(blank=True, to='community.posttag', verbose_name='태그'),
        ),
        migrations.AlterField(
            model_name='generalpost',
            name='title',
            field=models.CharField(max_length=200, verbose_name='제목'),
        ),
        migrations.AlterField(
            model_name='generalpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
        migrations.AlterField(
            model_name='generalpost',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='조회수'),
        ),
        migrations.AlterField(
            model_name='readinggrouppost',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community.book', verbose_name='책'),
        ),
        migrations.AlterField(
            model_name='readinggrouppost',
            name='category',
            field=models.CharField(choices=[('book_post', '책 게시글'), ('reading_group_post', '독서 모임'), ('book_review_event', '서평 이벤트'), ('book_talk_post', '북토크'), ('personal_event_post', '개인 이벤트')], default='book_post', help_text='게시글 유형 선택', max_length=50, verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='readinggrouppost',
            name='content',
            field=models.TextField(verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='readinggrouppost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='등록일'),
        ),
        migrations.AlterField(
            model_name='readinggrouppost',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='활성화 여부'),
        ),
        migrations.AlterField(
            model_name='readinggrouppost',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='삭제 여부'),
        ),
        migrations.AlterField(
            model_name='readinggrouppost',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='고정 여부'),
        ),
        migrations.AlterField(
            model_name='readinggrouppost',
            name='tags',
            field=models.ManyToManyField(blank=True, to='community.posttag', verbose_name='태그'),
        ),
        migrations.AlterField(
            model_name='readinggrouppost',
            name='title',
            field=models.CharField(max_length=200, verbose_name='제목'),
        ),
        migrations.AlterField(
            model_name='readinggrouppost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
        migrations.AlterField(
            model_name='readinggrouppost',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='조회수'),
        ),
        migrations.AlterField(
            model_name='readingtippost',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community.book', verbose_name='책'),
        ),
        migrations.AlterField(
            model_name='readingtippost',
            name='category',
            field=models.CharField(choices=[('book_post', '책 게시글'), ('reading_group_post', '독서 모임'), ('book_review_event', '서평 이벤트'), ('book_talk_post', '북토크'), ('personal_event_post', '개인 이벤트')], default='book_post', help_text='게시글 유형 선택', max_length=50, verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='readingtippost',
            name='content',
            field=models.TextField(verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='readingtippost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='등록일'),
        ),
        migrations.AlterField(
            model_name='readingtippost',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='활성화 여부'),
        ),
        migrations.AlterField(
            model_name='readingtippost',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='삭제 여부'),
        ),
        migrations.AlterField(
            model_name='readingtippost',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='고정 여부'),
        ),
        migrations.AlterField(
            model_name='readingtippost',
            name='tags',
            field=models.ManyToManyField(blank=True, to='community.posttag', verbose_name='태그'),
        ),
        migrations.AlterField(
            model_name='readingtippost',
            name='title',
            field=models.CharField(max_length=200, verbose_name='제목'),
        ),
        migrations.AlterField(
            model_name='readingtippost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
        migrations.AlterField(
            model_name='readingtippost',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='조회수'),
        ),
    ]
