# Generated by Django 5.1.4 on 2025-02-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_recommended',
            field=models.BooleanField(default=False, help_text='추천도서 페이지 노출 여부', verbose_name='추천도서 여부'),
        ),
        migrations.AddField(
            model_name='book',
            name='recommendation_comment',
            field=models.CharField(blank=True, help_text='추천도서 페이지에 표시될 짧은 설명 (150자 이내)', max_length=255, null=True, verbose_name='추천 코멘트'),
        ),
    ]
