# Generated by Django 5.1.4 on 2025-02-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_generalpost_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='좋아요 수'),
        ),
    ]
