# Generated by Django 5.1.4 on 2025-02-06 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_remove_book_genre_alter_bookgenre_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookgenre',
            options={},
        ),
        migrations.RemoveField(
            model_name='bookgenre',
            name='name',
        ),
        migrations.RemoveField(
            model_name='bookgenre',
            name='slug',
        ),
    ]
