# Generated by Django 5.1.4 on 2025-02-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_book_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookeventpost',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='좋아요 수'),
        ),
        migrations.AddField(
            model_name='generalpost',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='좋아요 수'),
        ),
        migrations.AddField(
            model_name='readinggrouppost',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='좋아요 수'),
        ),
        migrations.AddField(
            model_name='readingtippost',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='좋아요 수'),
        ),
    ]
