# Generated by Django 5.1.4 on 2025-02-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_alter_bookgenre_options_remove_bookgenre_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('에세이', 'essay'), ('소설', 'fiction'), ('비문학', 'non_fiction'), ('과학', 'science'), ('시', 'poetry')], default='에세이', help_text='책 장르 선택', max_length=50, verbose_name='책 장르'),
        ),
        migrations.DeleteModel(
            name='BookGenre',
        ),
    ]
