# Generated by Django 5.1.4 on 2025-02-01 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_bookeventpost_likes_generalpost_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookeventpost',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_posts', to='community.book', verbose_name='책'),
        ),
        migrations.AlterField(
            model_name='generalpost',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_posts', to='community.book', verbose_name='책'),
        ),
        migrations.AlterField(
            model_name='readinggrouppost',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_posts', to='community.book', verbose_name='책'),
        ),
        migrations.AlterField(
            model_name='readingtippost',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_posts', to='community.book', verbose_name='책'),
        ),
    ]
