# Generated by Django 5.1.4 on 2025-02-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_alter_book_genre_delete_bookgenre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('essay', '에세이'), ('fiction', '소설'), ('non_fiction', '비문학'), ('science', '과학'), ('poetry', '시')], default='essay', help_text='책 장르 선택', max_length=50, verbose_name='책 장르'),
        ),
    ]
