# Generated by Django 5.1.4 on 2025-01-27 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_alter_post_writer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='priority',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='낮은 숫자가 더 높은 우선순위(1 > 2), 미설정시 자동 정렬', null=True, verbose_name='우선순위'),
        ),
        migrations.AlterField(
            model_name='post',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
