# Generated by Django 5.1.4 on 2025-02-01 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_remove_bookrevieweventpost_bookeventpost_ptr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookrevieweventpost',
            name='event_end_date',
        ),
        migrations.RemoveField(
            model_name='bookrevieweventpost',
            name='event_start_date',
        ),
        migrations.RemoveField(
            model_name='booktalkeventpost',
            name='event_end_date',
        ),
        migrations.RemoveField(
            model_name='booktalkeventpost',
            name='event_start_date',
        ),
        migrations.RemoveField(
            model_name='personalbookeventpost',
            name='event_end_date',
        ),
        migrations.RemoveField(
            model_name='personalbookeventpost',
            name='event_start_date',
        ),
    ]
