# Generated by Django 5.1.4 on 2025-02-05 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_remove_bookrevieweventpost_event_end_date_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrevieweventpost',
            name='event_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='이벤트 종료일시'),
        ),
        migrations.AddField(
            model_name='bookrevieweventpost',
            name='event_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='이벤트 시작일시'),
        ),
        migrations.AddField(
            model_name='booktalkeventpost',
            name='event_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='이벤트 종료일시'),
        ),
        migrations.AddField(
            model_name='booktalkeventpost',
            name='event_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='이벤트 시작일시'),
        ),
        migrations.AddField(
            model_name='personalbookeventpost',
            name='event_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='이벤트 종료일시'),
        ),
        migrations.AddField(
            model_name='personalbookeventpost',
            name='event_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='이벤트 시작일시'),
        ),
        migrations.AlterField(
            model_name='bookrevieweventpost',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community.book', verbose_name='책'),
        ),
        migrations.AlterField(
            model_name='bookrevieweventpost',
            name='content',
            field=models.TextField(verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='bookrevieweventpost',
            name='title',
            field=models.CharField(max_length=200, verbose_name='제목'),
        ),
        migrations.AlterField(
            model_name='booktalkeventpost',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community.book', verbose_name='책'),
        ),
        migrations.AlterField(
            model_name='booktalkeventpost',
            name='content',
            field=models.TextField(verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='booktalkeventpost',
            name='title',
            field=models.CharField(max_length=200, verbose_name='제목'),
        ),
        migrations.AlterField(
            model_name='generalpost',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community.book', verbose_name='책'),
        ),
        migrations.AlterField(
            model_name='generalpost',
            name='content',
            field=models.TextField(verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='generalpost',
            name='title',
            field=models.CharField(max_length=200, verbose_name='제목'),
        ),
        migrations.AlterField(
            model_name='personalbookeventpost',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community.book', verbose_name='책'),
        ),
        migrations.AlterField(
            model_name='personalbookeventpost',
            name='content',
            field=models.TextField(verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='personalbookeventpost',
            name='title',
            field=models.CharField(max_length=200, verbose_name='제목'),
        ),
        migrations.AlterField(
            model_name='readinggrouppost',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community.book', verbose_name='책'),
        ),
        migrations.AlterField(
            model_name='readinggrouppost',
            name='content',
            field=models.TextField(verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='readinggrouppost',
            name='title',
            field=models.CharField(max_length=200, verbose_name='제목'),
        ),
        migrations.AlterField(
            model_name='readingtippost',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community.book', verbose_name='책'),
        ),
        migrations.AlterField(
            model_name='readingtippost',
            name='content',
            field=models.TextField(verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='readingtippost',
            name='title',
            field=models.CharField(max_length=200, verbose_name='제목'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='community.comment')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
        ),
    ]
