# Generated by Django 5.1.4 on 2025-02-11 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_alter_comment_options_comment_depth_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='bookrevieweventpost',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='booktalkeventpost',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='generalpost',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='personalbookeventpost',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='readinggrouppost',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='readingtippost',
            name='likes',
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='community_l_content_846b74_idx')],
                'unique_together': {('user', 'content_type', 'object_id')},
            },
        ),
    ]
